import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# 1. Pull the exact variable strings you just exported into your Gentoo shell
API_KEY = os.environ.get("CORPORATE_EMAIL_API_KEY")
SENDER_EMAIL = os.environ.get("CORPORATE_SENDER_EMAIL")
RECIPIENT_EMAIL = os.environ.get("CUSTOMER_DESTINATION_EMAIL")

def main():
    print("📨 Delivery Bot activated by pipeline compiler...")
    
    # Structural check prevents empty variable crashes
    if not API_KEY or not SENDER_EMAIL or not RECIPIENT_EMAIL:
        print("\n❌ CRITICAL STOP: Missing system environment variables!")
        print(f"   - CORPORATE_EMAIL_API_KEY: {'Loaded ✅' if API_KEY else 'MISSING ❌'}")
        print(f"   - CORPORATE_SENDER_EMAIL: {'Loaded ✅' if SENDER_EMAIL else 'MISSING ❌'}")
        print(f"   - CUSTOMER_DESTINATION_EMAIL: {'Loaded ✅' if RECIPIENT_EMAIL else 'MISSING ❌'}\n")
        return

    # Read your live digital product generated by your asset bot
    try:
        with open("market_intelligence.md", "r") as f:
            report_content = f.read()
    except FileNotFoundError:
        print("❌ Delivery Aborted: 'market_intelligence.md' file not found on drive.")
        return

    # Set up the secure outbound email content container
    msg = MIMEMultipart()
    msg['From'] = SENDER_EMAIL
    msg['To'] = RECIPIENT_EMAIL
    msg['Subject'] = "📊 Your Automated Global Market Intelligence Report"
    msg.attach(MIMEText(report_content, 'plain'))

    try:
        print(f"🔒 Connecting to secure SMTP gateway: smtp.resend.com...")
        # Resend SMTP utilizes port 587 with explicit TLS encryption
        server = smtplib.SMTP("smtp.resend.com", 587)
        server.starttls()
        
        print("🔑 Authenticating api token credentials...")
        # Resend requires the literal string "resend" as the login username
        server.login("resend", API_KEY)
        
        print(f"🚀 Shipping asset payload to client inbox: {RECIPIENT_EMAIL}...")
        server.sendmail(SENDER_EMAIL, RECIPIENT_EMAIL, msg.as_string())
        server.quit()
        print("✅ Success! Data asset securely delivered to client inbox.")
    except Exception as e:
        print(f"❌ Network transmission failed: {e}")

if __name__ == "__main__":
    main()
