#!/usr/bin/env python3
"""
marketing_bot.py
Dynamically extracts trending insights from the freshest generated report 
and outputs copy for automated distributions or terminal verification.
"""
import os
import glob
import logging

# Configure standardized logging metrics
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def get_market_intelligence_teaser() -> str:
    """Dynamically finds the newest generated analyst report and extracts top sections."""
    try:
        # Match files matching your analyst bot's naming convention
        report_files = glob.glob('analyst_article_*.md')
        
        # Fallback support if manually saved under the flat name
        if os.path.exists('market_intelligence.md'):
            report_files.append('market_intelligence.md')
            
        if not report_files:
            logging.warning("No generated report files found matching patterns.")
            return "System Analytics Assembly Engine (Compiling...)"
            
        # Sort files by modification time to extract the absolute freshest data block
        latest_file = max(report_files, key=os.path.getmtime)
        logging.info(f"📊 Extracting promotional teaser highlights from: {latest_file}")
        
        with open(latest_file, 'r', encoding='utf-8') as file:
            lines = file.readlines()
        
        project_names = []
        for line in lines:
            # Match top structural H2 titles generated by the analyst bot
            if line.startswith('## '):
                name = line.replace('##', '').strip()
                if name:
                    project_names.append(name)
                    
        if project_names:
            # Returns the top core analytical sections found in your generated report
            return ' | '.join(project_names[:3])
            
        return "Latest Open-Source Global Trends Matrix"
        
    except Exception as e:
        logging.error(f"Error reading report repository indexes: {e}")
        return "System Analytics Assembly Engine (Compiling...)"

def main():
    teaser = get_market_intelligence_teaser()
    
    # Secure Solana Pay Transaction Route
    PAY_URL = "solana:3rLapKiA4SfTQMMMFfkZSfkT12iFXQPiKv7w9mzqKZqh?amount=0.01&label=Global%20Market%20Intelligence%20Report&memo=Enter_Your_Email_In_Wallet_Memo"

    print("\n📣 --- NEW AUTOMATED CONTENT BROADCAST --- 📣")
    print(f"📈 Strategic intelligence vectors compiled this session:\n👉 {teaser}\n")
    print("💎 Want the full, deep-dive Technical Metrics Report mailed straight to your inbox?")
    print(f"🔗 Scan or click our secure Solana Pay Link to unlock instant delivery:\n👉 {PAY_URL}\n")
    print("⚠️ IMPORTANT: Type your destination email address directly into your wallet's 'MEMO' field before confirming the transfer so our delivery agent knows where to ship your report!")
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n")

if __name__ == "__main__":
    main()
